Repository SOLPLY/SOLPLY-ANDROID, pull requests merged in 2025-07, with the labels that each got.

#39 [feature#38] Onboarding component
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/component/ProgressBar.kt
Labels: enhancement, 시현🥐🐟

#63 [Feature/#60] maps dialog
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsContract.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsScreen.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsViewModel.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/CourseItem.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/MapsTopBar.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/AddCourseBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/EditCourseBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/PlaceDetailBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/dialog/CourseSaveDialog.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/model/CourseSaveType.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/util/CameraPositionUtil.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/util/DragDropExtension.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/util/DragDropState.kt
Labels: 석찬🍚🦁

#69 [Feature/#66] refactor onboarding
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/header/SolplyCourseHeader.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/textfield/SolplyTextField.kt
  feature/course/src/main/java/com/teamsolply/solply/course/CourseScreen.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainNavigator.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/component/BackHeader.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/navigation/OnBoardingNavigation.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/NamingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/SelectPersonaScreen.kt
Labels: 시현🥐🐟

#76 [Feature/#74] login api
  .gitignore
  app/build.gradle.kts
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/textfield/SolplyTextField.kt
  core/network/src/main/java/com/teamsolply/solply/network/AccessTokenInterceptor.kt
  core/network/src/main/java/com/teamsolply/solply/network/service/TokenRefreshService.kt
  data/oauth/src/main/java/com/teamsolply/solply/oauth/dto/request/SocialLoginRequestDto.kt
  data/oauth/src/main/java/com/teamsolply/solply/oauth/dto/response/SocialLoginResponseDto.kt
  data/oauth/src/main/java/com/teamsolply/solply/oauth/repository/OauthRepositoryImpl.kt
  data/oauth/src/main/java/com/teamsolply/solply/oauth/source/OauthRemoteDataSource.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/dto/request/PatchUserInfoRequestDto.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/dto/response/NicknameDuplicateResponseDto.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/dto/response/PatchUserInfoResponseDto.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/repository/OnBoardingRepositoryImpl.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/source/OnBoardingRemoteDataSource.kt
  domain/oauth/src/main/java/com/teamsolply/solply/oauth/model/TokenEntity.kt
  domain/oauth/src/main/java/com/teamsolply/solply/oauth/repository/OauthRepository.kt
  domain/onboarding/src/main/java/com/teamsolply/solply/onboarding/model/SignUpEntity.kt
  domain/onboarding/src/main/java/com/teamsolply/solply/onboarding/model/UserInfoEntity.kt
  domain/onboarding/src/main/java/com/teamsolply/solply/onboarding/repository/OnBoardingRepository.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainNavigator.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainScreen.kt
  feature/oauth/src/main/java/com/teamsolply/solply/oauth/OauthContract.kt
  feature/oauth/src/main/java/com/teamsolply/solply/oauth/OauthScreen.kt
  feature/oauth/src/main/java/com/teamsolply/solply/oauth/OauthViewModel.kt
  feature/oauth/src/main/java/com/teamsolply/solply/oauth/navigation/OauthNavigation.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/OnBoardingContract.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/OnBoardingViewModel.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/component/BackHeader.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/navigation/OnBoardingNavigation.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/NamingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/SelectPersonaScreen.kt
  remote/oauth/.gitignore
  remote/oauth/build.gradle.kts
  remote/oauth/src/main/java/com/teamsolply/solply/oauth/datasource/OauthRemoteDataSourceImpl.kt
  remote/oauth/src/main/java/com/teamsolply/solply/oauth/di/OauthRemoteDataModule.kt
  remote/oauth/src/main/java/com/teamsolply/solply/oauth/di/OauthServiceModule.kt
  remote/oauth/src/main/java/com/teamsolply/solply/oauth/service/OauthService.kt
  remote/onboarding/src/main/java/com/teamsolply/solply/onboarding/datasource/OnBoardingRemoteDataSourceImpl.kt
  remote/onboarding/src/main/java/com/teamsolply/solply/onboarding/service/OnBoardingService.kt
  settings.gradle.kts
Labels: 석찬🍚🦁

#79 [Feature/#73] mypage api
  app/build.gradle.kts
  data/mypage/src/main/java/com/teamsolply/solply/mypage/dto/response/CourseListResponseDto.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/dto/response/CourseTownListResponseDto.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/dto/response/PlaceListResponseDto.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/dto/response/PlaceTownListResponseDto.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/dto/response/UserInfoResponseDto.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/repository/MypageRepositoryImpl.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/source/MypageRemoteDataSource.kt
  domain/mypage/src/main/java/com/teamsolply/solply/mypage/model/CourseInfoEntity.kt
  domain/mypage/src/main/java/com/teamsolply/solply/mypage/model/CourseTownEntity.kt
  domain/mypage/src/main/java/com/teamsolply/solply/mypage/model/PlaceInfoEntity.kt
  domain/mypage/src/main/java/com/teamsolply/solply/mypage/model/PlaceTownEntity.kt
  domain/mypage/src/main/java/com/teamsolply/solply/mypage/model/UserInfoEntity.kt
  domain/mypage/src/main/java/com/teamsolply/solply/mypage/repository/MypageRepository.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainNavigator.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageContract.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageViewModel.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/component/CollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionContract.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionNavigator.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionViewModel.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionContract.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionNavigation.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionViewModel.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/CourseTownCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/PlaceTownCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/TabScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/TownCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/navigation/MypageNavigation.kt
  remote/mypage/src/main/java/com/teamsolply/solply/mypage/datasource/MypageRemoteDataSourceImpl.kt
  remote/mypage/src/main/java/com/teamsolply/solply/mypage/service/MypageService.kt
Labels: 형석 🐧🍀

#80 [Feature/#77] onboarding, maps api
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/textfield/SolplyTextField.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/teamsolply/solply/ui/image/AdaptationImage.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/dto/SaveCourseRequestDto.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/dto/response/GetAddMyCourseResponseDto.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/dto/response/GetCourseDetailResponseDto.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/dto/response/GetPlaceDetailResponseDto.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/mapper/CourseDetailEntityMapper.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/mapper/CourseInfoEntityMapper.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/mapper/PlaceDetailEntityMapper.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/repository/MapsRepositoryImpl.kt
  data/maps/src/main/java/com/teamsolply/solply/maps/source/MapsRemoteDataSource.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/dto/response/GetPersonaQuestionsResponseDto.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/mapper/PersonaEntityMapper.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/repository/OnBoardingRepositoryImpl.kt
  data/onboarding/src/main/java/com/teamsolply/solply/onboarding/source/remote/OnBoardingRemoteDataSource.kt
  domain/maps/src/main/java/com/teamsolply/solply/maps/model/CourseDetailEntity.kt
  domain/maps/src/main/java/com/teamsolply/solply/maps/model/CourseInfoEntity.kt
  domain/maps/src/main/java/com/teamsolply/solply/maps/model/PlaceDetailEntity.kt
  domain/maps/src/main/java/com/teamsolply/solply/maps/repository/MapsRepository.kt
  domain/onboarding/src/main/java/com/teamsolply/solply/onboarding/model/PersonaEntity.kt
  domain/onboarding/src/main/java/com/teamsolply/solply/onboarding/repository/OnBoardingRepository.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsContract.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsScreen.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsViewModel.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/AddCourseBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/EditCourseBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/PlaceDetailBottomSheet.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/OnBoardingContract.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/OnBoardingViewModel.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/NamingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/SelectPersonaScreen.kt
  gradle/libs.versions.toml
  remote/maps/src/main/java/com/teamsolply/solply/maps/datasource/MapsRemoteDataSourceImpl.kt
  remote/maps/src/main/java/com/teamsolply/solply/maps/service/MapsService.kt
  remote/onboarding/src/main/java/com/teamsolply/solply/onboarding/datasource/OnBoardingRemoteDataSourceImpl.kt
  remote/onboarding/src/main/java/com/teamsolply/solply/onboarding/di/OnBoardingRemoteDataModule.kt
  remote/onboarding/src/main/java/com/teamsolply/solply/onboarding/service/OnBoardingService.kt
Labels: 석찬🍚🦁

#82 [Feature/#73] fix course town api
  data/mypage/src/main/java/com/teamsolply/solply/mypage/dto/response/CourseTownListResponseDto.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/repository/MypageRepositoryImpl.kt
  domain/mypage/src/main/java/com/teamsolply/solply/mypage/repository/MypageRepository.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageContract.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageViewModel.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionContract.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionViewModel.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionContract.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionViewModel.kt
  remote/mypage/src/main/java/com/teamsolply/solply/mypage/datasource/MypageRemoteDataSourceImpl.kt
  remote/mypage/src/main/java/com/teamsolply/solply/mypage/service/MypageService.kt
Labels: 형석 🐧🍀

#78 [Feature/#75] splash UI
  core/designsystem/src/main/res/raw/finish_onboarding.json
  feature/course/src/main/java/com/teamsolply/solply/course/CourseScreen.kt
  feature/main/build.gradle.kts
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/teamsolply/solply/main/MainNavigator.kt
  feature/main/src/main/java/com/teamsolply/solply/main/splash/SplashScreen.kt
  feature/main/src/main/res/raw/splash.json
  feature/main/src/main/res/values-v31/themes.xml
  feature/main/src/main/res/values/themes.xml
  feature/oauth/src/main/java/com/teamsolply/solply/oauth/OauthScreen.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/SelectTownScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/StartingScreen.kt
Labels: 시현🥐🐟

#91 [Feature/#83] fix tag api
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyPlaceCard.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/SelectTownScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceContract.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceViewModel.kt
Labels: 형석 🐧🍀

#92 [Chore/#88] design detail
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/button/SolplyButton.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/header/SolplyCourseHeader.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/snackbar/SolplySnackBar.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/textfield/SolplyTextField.kt
  core/designsystem/src/main/res/drawable/img_login_graphic.xml
  feature/course/src/main/java/com/teamsolply/solply/course/CourseScreen.kt
  feature/main/src/main/java/com/teamsolply/solply/main/component/MainBottomBar.kt
  feature/oauth/src/main/java/com/teamsolply/solply/oauth/OauthScreen.kt
Labels: 나경🐹🍙

#93 [Feature/#90] place api connect
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyPlaceCard.kt
  data/place/src/main/java/com/teamsolply/solply/place/dto/response/GetPlacesResponseDto.kt
  data/place/src/main/java/com/teamsolply/solply/place/mapper/PlaceEntityMapper.kt
  data/place/src/main/java/com/teamsolply/solply/place/repository/PlaceRepositoryImpl.kt
  data/place/src/main/java/com/teamsolply/solply/place/source/PlaceRemoteDataSource.kt
  domain/place/src/main/java/com/teamsolply/solply/place/model/PlaceEntity.kt
  domain/place/src/main/java/com/teamsolply/solply/place/repository/PlaceRepository.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainNavigator.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainScreen.kt
  feature/main/src/main/java/com/teamsolply/solply/main/component/MainBottomBar.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsScreen.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/PlaceDetailBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/navigation/MapsNavigation.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceContract.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceViewModel.kt
  feature/place/src/main/java/com/teamsolply/solply/place/model/PlaceData.kt
  feature/place/src/main/java/com/teamsolply/solply/place/navigation/PlaceNavigation.kt
  remote/place/src/main/java/com/teamsolply/solply/place/datasource/PlaceRemoteDataSourceImpl.kt
  remote/place/src/main/java/com/teamsolply/solply/place/service/PlaceService.kt
Labels: 석찬🍚🦁

#98 [Chore/#96] design qa & detail
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyCourseCard.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyPlaceCard.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/header/SolplyCourseHeader.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/topbar/SolplyTopBar.kt
  feature/course/src/main/java/com/teamsolply/solply/course/CourseScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/NamingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/StartingScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/component/header/SolplyPlaceHeader.kt
Labels: 나경🐹🍙

#99 [Feature/#94] 장소 API 컽!
  data/place/src/main/java/com/teamsolply/solply/place/repository/PlaceRepositoryImpl.kt
  data/place/src/main/java/com/teamsolply/solply/place/source/PlaceRemoteDataSource.kt
  domain/place/src/main/java/com/teamsolply/solply/place/repository/PlaceRepository.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceContract.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceViewModel.kt
  feature/place/src/main/java/com/teamsolply/solply/place/component/bottomsheet/PlaceOptionFilterSheet.kt
  remote/course/src/main/java/com/teamsolply/solply/course/service/CourseService.kt
  remote/place/src/main/java/com/teamsolply/solply/place/datasource/PlaceRemoteDataSourceImpl.kt
  remote/place/src/main/java/com/teamsolply/solply/place/service/PlaceService.kt
Labels: 형석 🐧🍀

#104 [Refactor/#103] fix collection place delete api
  core/network/src/main/java/com/teamsolply/solply/network/model/NullableBaseResponse.kt
  data/mypage/src/main/java/com/teamsolply/solply/mypage/source/MypageRemoteDataSource.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/place/PlaceCollectionViewModel.kt
  remote/mypage/src/main/java/com/teamsolply/solply/mypage/service/MypageService.kt
Labels: 형석 🐧🍀

#110 [Chore/#100] design detail 3
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyCourseCard.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/snackbar/SolplySnackBar.kt
  data/place/src/main/java/com/teamsolply/solply/place/repository/PlaceRepositoryImpl.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsScreen.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/PlaceDetailBottomSheet.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/component/CollectionScreen.kt
Labels: 나경🐹🍙

#108 [Feature/#84] town update api connect
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/header/SolplyCourseHeader.kt
  data/course/src/main/java/com/teamsolply/solply/course/favoriteTown/di/FavoriteTownDataModule.kt
  data/course/src/main/java/com/teamsolply/solply/course/favoriteTown/dto/FavoriteTownUserInfoResponseDto.kt
  data/course/src/main/java/com/teamsolply/solply/course/favoriteTown/dto/PatchUserFavTownRequestDto.kt
  data/course/src/main/java/com/teamsolply/solply/course/favoriteTown/repository/FavoriteTownRepositoryImpl.kt
  data/course/src/main/java/com/teamsolply/solply/course/favoriteTown/source/FavoriteTownRemoteDataSource.kt
  domain/course/src/main/java/com/teamsolply/solply/course/favoriteTown/model/FavoriteTownInfoEntity.kt
  domain/course/src/main/java/com/teamsolply/solply/course/favoriteTown/model/Town.kt
  domain/course/src/main/java/com/teamsolply/solply/course/favoriteTown/repository/FavoriteTownRepository.kt
  feature/course/src/main/java/com/teamsolply/solply/course/CourseScreen.kt
  feature/course/src/main/java/com/teamsolply/solply/course/component/FavoriteTownTopBar.kt
  feature/course/src/main/java/com/teamsolply/solply/course/favoriteTown/FavoriteTownContract.kt
  feature/course/src/main/java/com/teamsolply/solply/course/favoriteTown/FavoriteTownScreen.kt
  feature/course/src/main/java/com/teamsolply/solply/course/favoriteTown/FavoriteViewModel.kt
  feature/course/src/main/java/com/teamsolply/solply/course/favoriteTown/favoriteTownNavigation/FavoriteTownNavigation.kt
  feature/course/src/main/java/com/teamsolply/solply/course/favoriteTown/model/CourseState.kt
  feature/course/src/main/java/com/teamsolply/solply/course/favoriteTown/model/TownModel.kt
  feature/course/src/main/java/com/teamsolply/solply/course/navigation/CourseNavigation.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainNavigator.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/component/header/SolplyPlaceHeader.kt
  feature/place/src/main/java/com/teamsolply/solply/place/navigation/PlaceNavigation.kt
  remote/course/src/main/java/com/teamsolply/solply/course/favoriteTown/datasource/FavoriteTownRemoteDataSourceImpl.kt
  remote/course/src/main/java/com/teamsolply/solply/course/favoriteTown/di/FavoriteTownRemoteDataModule.kt
  remote/course/src/main/java/com/teamsolply/solply/course/favoriteTown/di/FavoriteTownServiceModule.kt
  remote/course/src/main/java/com/teamsolply/solply/course/favoriteTown/service/FavoriteTownService.kt
Labels: 시현🥐🐟

#112 [Feature/#109] first qa
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/button/SolplyButton.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyCourseCard.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyPlaceCard.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/snackbar/SolplySnackBar.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/topbar/SolplyTopBar.kt
  core/model/src/main/java/com/teamsolply/solply/model/SnackBarType.kt
  core/ui/src/main/java/com/teamsolply/solply/ui/image/AdaptationImage.kt
  feature/course/src/main/java/com/teamsolply/solply/course/CourseScreen.kt
  feature/main/src/main/java/com/teamsolply/solply/main/MainScreen.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsContract.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsScreen.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsViewModel.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/MapsTopBar.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/PlaceDetailBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/navigation/MapsNavigation.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/MypageScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/course/CourseCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/CourseTownCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/SolplyTownCard.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/navigation/MypageNavigation.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceContract.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceSkeletonCard.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceViewModel.kt
  feature/place/src/main/java/com/teamsolply/solply/place/component/header/SolplyPlaceHeader.kt
Labels: 석찬🍚🦁

#115 [Chore/#113] 최종 QA
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/card/SolplyCourseCard.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/dialog/SolplyConfirmDialog.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/snackbar/SolplySnackBar.kt
  core/designsystem/src/main/java/com/teamsolply/solply/designsystem/component/textfield/SolplyTextField.kt
  feature/course/src/main/java/com/teamsolply/solply/course/CourseScreen.kt
  feature/main/src/main/java/com/teamsolply/solply/main/splash/SplashViewModel.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/CourseItem.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/collection/component/CollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/EmptyCollectionScreen.kt
  feature/mypage/src/main/java/com/teamsolply/solply/mypage/component/SolplyTownCard.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/component/ProgressBar.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/NamingScreen.kt
  feature/onboarding/src/main/java/com/teamsolply/solply/onboarding/screen/SelectPersonaScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/PlaceScreen.kt
  feature/place/src/main/java/com/teamsolply/solply/place/component/card/PlaceRecommendCard.kt
Labels: 나경🐹🍙

#120 [Feature/#116] first qa
  core/ui/src/main/java/com/teamsolply/solply/ui/text/TextUtil.kt
  feature/main/src/main/res/values/strings.xml
  feature/maps/src/main/java/com/teamsolply/solply/maps/MapsScreen.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/CourseItem.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/EditCourseBottomSheet.kt
  feature/maps/src/main/java/com/teamsolply/solply/maps/component/bottomsheet/PlaceDetailBottomSheet.kt
Labels: 석찬🍚🦁

#123 chore Update README 파일
  README.md
Labels: 나경🐹🍙
